apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: frontend-unit-test-pipeline 
  name: frontend-unit-test-pipeline
spec:
  source:
    type: Git
    git:
      uri: https://github.com/juhtornr/LocalEGA.git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile

